name: 各地天氣狀況


on:

  schedule:
    - cron: '* 0/8 * * *'

  workflow_dispatch:

jobs:
  edit:
    runs-on: ubuntu-latest
    
    steps:

      - uses: actions/checkout@v4

      - name: 安裝Python
        uses: actions/setup-python@v5.1.1

      - name: 編輯檔案
        run: python main.py
        env:
          WEATHER: ${{ secrets.WEATHER }}

      - name: 送出變更

        run: |
          git config --global user.email $email
          git config --global user.name $username
          git add README.md
          git commit -m "更新天氣資訊($time)"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          email: ${{ vars.email }}
          username: ${{ vars.username }}
          time: ${{ steps.time.outputs.time}}
          
